feat: Add support for gVisor per node pool
terraform-google-modules/terraform-google-kubernetes-engine pull request #1001
Opened 2021-09-16 13:43 UTC by LukaszCzarnotaSabre

Issue [https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/240](url) was resolved but now all node pools needs to be with gVisor or non of them.

With this PR you are able to define `sandbox_enabled` variable per node pool, code is backward compatible.

2021-09-16 13:46 UTC, LukaszCzarnotaSabre commented
@googlebot I signed it!

2021-09-16 15:05 UTC, Jberlinsky commented
@LukaszCzarnotaSabre Looks like this change is causing test failures:

```
Step #48 - "converge node-pool-local":        Error: Invalid index
Step #48 - "converge node-pool-local":        
Step #48 - "converge node-pool-local":          on ../../../modules/beta-public-cluster/cluster.tf line 423, in resource "google_container_node_pool" "pools":
Step #48 - "converge node-pool-local":         423:       for_each = tobool((lookup(each.value, "sandbox_enabled", ((local.cluster_sandbox_enabled[0] == "gvisor") ? true : false)))) ? ["gvisor"] : []
Step #48 - "converge node-pool-local":            ├────────────────
Step #48 - "converge node-pool-local":            │ local.cluster_sandbox_enabled is empty list of string
Step #48 - "converge node-pool-local":        
Step #48 - "converge node-pool-local":        The given key does not identify an element in this collection value: the
Step #48 - "converge node-pool-local":        collection has no elements.
Step #9 - "converge safer-cluster-local":        
Step #9 - "converge safer-cluster-local":        Error: Invalid index
Step #9 - "converge safer-cluster-local":        
Step #9 - "converge safer-cluster-local":          on ../../../modules/beta-private-cluster/cluster.tf line 442, in resource "google_container_node_pool" "pools":
Step #9 - "converge safer-cluster-local":         442:       for_each = tobool((lookup(each.value, "sandbox_enabled", ((local.cluster_sandbox_enabled[0] == "gvisor") ? true : false)))) ? ["gvisor"] : []
Step #9 - "converge safer-cluster-local":            ├────────────────
Step #9 - "converge safer-cluster-local":            │ local.cluster_sandbox_enabled is empty list of string
Step #9 - "converge safer-cluster-local":        
Step #9 - "converge safer-cluster-local":        The given key does not identify an element in this collection value: the
Step #9 - "converge safer-cluster-local":        collection has no elements.
Step #48 - "converge node-pool-local":        
Step #48 - "converge node-pool-local":        Error: Invalid index
Step #48 - "converge node-pool-local":        
Step #48 - "converge node-pool-local":          on ../../../modules/beta-public-cluster/cluster.tf line 423, in resource "google_container_node_pool" "pools":
Step #48 - "converge node-pool-local":         423:       for_each = tobool((lookup(each.value, "sandbox_enabled", ((local.cluster_sandbox_enabled[0] == "gvisor") ? true : false)))) ? ["gvisor"] : []
Step #48 - "converge node-pool-local":            ├────────────────
Step #48 - "converge node-pool-local":            │ local.cluster_sandbox_enabled is empty list of string
Step #48 - "converge node-pool-local":        
Step #48 - "converge node-pool-local":        The given key does not identify an element in this collection value: the
Step #48 - "converge node-pool-local":        collection has no elements.
Step #30 - "converge stub-domains-local":        google_compute_network.main: Creating...
Step #9 - "converge safer-cluster-local": >>>>>> Running the command `terraform apply -auto-approve -lock=true -lock-timeout=0s -input=false -no-color -parallelism=10 -refresh=true  ` failed due to a non-zero exit code of 1.
Step #9 - "converge safer-cluster-local": >>>>>> ------Exception-------
Step #9 - "converge safer-cluster-local": >>>>>> Class: Kitchen::ActionFailed
Step #9 - "converge safer-cluster-local": >>>>>> Message: 1 actions failed.
Step #9 - "converge safer-cluster-local": >>>>>>     Converge failed on instance <safer-cluster-local>.  Please see .kitchen/logs/safer-cluster-local.log for more details
Step #9 - "converge safer-cluster-local": >>>>>> ----------------------
Step #9 - "converge safer-cluster-local": >>>>>> Please see .kitchen/logs/kitchen.log for more details
Step #9 - "converge safer-cluster-local": >>>>>> Also try running `kitchen diagnose --all` for configuration
Step #48 - "converge node-pool-local":        
Step #48 - "converge node-pool-local":        Error: Invalid index
Step #48 - "converge node-pool-local":        
Step #48 - "converge node-pool-local":          on ../../../modules/beta-public-cluster/cluster.tf line 423, in resource "google_container_node_pool" "pools":
Step #48 - "converge node-pool-local":         423:       for_each = tobool((lookup(each.value, "sandbox_enabled", ((local.cluster_sandbox_enabled[0] == "gvisor") ? true : false)))) ? ["gvisor"] : []
Step #48 - "converge node-pool-local":            ├────────────────
Step #48 - "converge node-pool-local":            │ local.cluster_sandbox_enabled is empty list of string
Step #48 - "converge node-pool-local":        
```

Could you please update tests to make sure they're compliant with this change?

2021-09-16 16:28 UTC, bharathkkb requested changes
Thanks for the PR! It would also be great to add this to [one of our tests](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/node_pool_update_variant/main.tf) to make sure its WAI

2021-09-16 16:28 UTC, bharathkkb commented on autogen/main/cluster.tf.tmpl
> +      for_each = tobool((lookup(each.value, "sandbox_enabled", ((local.cluster_sandbox_enabled[0] == "gvisor") ? true : false)))) ? ["gvisor"] : []
We could use the `sandbox_enabled` variable as the default (as opposed to using `local.cluster_sandbox_enabled[0]`) which would simplify this logic.

2021-09-27 23:33 UTC, bharathkkb commented
@googlebot I consent.

2021-09-28 00:16 UTC, bharathkkb commented
/cc @morgante for another pass since I have a commit in here

2021-09-28 00:20 UTC, morgante approved these changes

2021-09-28 00:20 UTC, merged