Remove deprecation warning about identity_namespace
terraform-google-modules/terraform-google-kubernetes-engine pull request #1052
Opened 2021-11-04 17:33 UTC by lra

Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1051

2021-11-04 17:34 UTC, lra commented
@googlebot I signed it!

2021-11-04 18:17 UTC, lra commented
I feel this is because the google provider v4.0.0 is required for this, should I make this bold move?git

2021-11-05 00:01 UTC, bharathkkb requested changes
Thanks for the PR @lra

2021-11-05 00:01 UTC, bharathkkb commented on autogen/main/versions.tf.tmpl
> -      version = ">= 3.79.0, <4.0.0"
I believe we can constrain this to 3.90 based on https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md#3900-october-26-2021

2021-11-05 00:08 UTC, bharathkkb commented
> I feel this is because the google provider v4.0.0 is required for this, should I make this bold move?

We generally try to delay **requiring** an updated provider, especially a major release, so users can adapt their other configs. 

We can remove the `<4.0.0` though and allow users to try this module with 4.0 provider (if you have bandwidth, feel free to submit this as *a separate PR* - I think there [maybe a few other changes](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_4_upgrade#resource-google_container_cluster) we may need to address in that)

2021-11-06 12:38 UTC, lra commented
Is it possible to have access to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1052/checks?check_run_id=4122394008 ?
Because I struggle with the local setup, it takes hours to run (I'm on arm64 so it's running emulated) and I have weird unrelated errors like:
```
       │ Error: local-exec provisioner error
       │ 
       │   with module.example.module.acm.module.acm_operator.module.k8s_operator.module.gcloud_kubectl.null_resource.run_command[0],
       │   on .terraform/modules/example.acm.acm_operator.k8s_operator/main.tf line 231, in resource "null_resource" "run_command":
       │  231:   provisioner "local-exec" {
       │ 
       │ Error running command 'PATH=/google-cloud-sdk/bin:$PATH
       │ .terraform/modules/example.acm.acm_operator.k8s_operator/modules/kubectl-wrapper/scripts/kubectl_wrapper.sh
       │ simple-zonal-cluster-fosf us-central1-a ci-gke-d1ce8521-3534 false false
       │ kubectl apply -f /workspace/acm.yaml
       │ ': exit status 1. Output: + '[' 9 -lt 5 ']'
       │ + CLUSTER_NAME=simple-zonal-cluster-fosf
       │ + LOCATION=us-central1-a
       │ + PROJECT_ID=ci-gke-d1ce8521-3534
       │ + INTERNAL=false
       │ + USE_EXISTING_CONTEXT=false
       │ + ENABLE_IMPERSONATE_SERVICE_ACCOUNT=kubectl
       │ + IMPERSONATE_SERVICE_ACCOUNT=apply
       │ + shift 5
       │ + false
       │ + RANDOM_ID=6123_18147
       │ + export TMPDIR=/tmp/kubectl_wrapper_6123_18147
       │ + TMPDIR=/tmp/kubectl_wrapper_6123_18147
       │ + trap cleanup EXIT
       │ + mkdir /tmp/kubectl_wrapper_6123_18147
       │ + export KUBECONFIG=/tmp/kubectl_wrapper_6123_18147/config
       │ + KUBECONFIG=/tmp/kubectl_wrapper_6123_18147/config
       │ ++ wc -l
       │ ++ grep -o -
       │ + LOCATION_TYPE=2
       │ + CMD='gcloud container clusters get-credentials simple-zonal-cluster-fosf
       │ --project ci-gke-d1ce8521-3534'
       │ + [[ kubectl == true ]]
       │ + [[ 2 -eq 2 ]]
       │ + CMD+=' --zone us-central1-a'
       │ + false
       │ + gcloud container clusters get-credentials simple-zonal-cluster-fosf
       │ --project ci-gke-d1ce8521-3534 --zone us-central1-a
       │ Fetching cluster endpoint and auth data.
       │ kubeconfig entry generated for simple-zonal-cluster-fosf.
       │ + kubectl apply -f /workspace/acm.yaml
       │ error: the path "/workspace/acm.yaml" does not exist
       │ + cleanup
       │ + rm -rf /tmp/kubectl_wrapper_6123_18147
```

2021-11-08 20:56 UTC, morgante commented
Unfortunately it's not possible to share Cloud Build logs, but this is the error:
```
       Error: Incorrect attribute value type
       
         on ../../../modules/beta-public-cluster/cluster.tf line 430, in resource "google_container_node_pool" "pools":
        430:     guest_accelerator = [
        431:       for guest_accelerator in lookup(each.value, "accelerator_count", 0) > 0 ? [{
        432:         type  = lookup(each.value, "accelerator_type", "")
        433:         count = lookup(each.value, "accelerator_count", 0)
        434:         }] : [] : {
        435:         type  = guest_accelerator["type"]
        436:         count = guest_accelerator["count"]
        437:       }
        438:     ]
           ├────────────────
           │ each.value is map of string with 12 elements
```

2022-01-08 02:51 UTC, morgante commented
@lra Are you planning to continue work on this?

2022-01-08 14:11 UTC, lra commented
It's hard for me because I'm on arm64 and it's taking hours to get errors out of each run =(

2022-03-17 23:16 UTC, closed without merging