feat: GKE autopilot support
terraform-google-modules/terraform-google-kubernetes-engine pull request #1148
Opened 2022-02-10 21:55 UTC by jmymy

2022-02-15 01:18 UTC, jmymy commented
@cmcga1125 can you sign the CLA? If you want credit on the PR. Otherwise I'll have to remove your commits from the PR.

2022-02-15 01:18 UTC, jmymy commented
@bharathkkb any insight on what kitchen test is failing?

2022-02-15 03:42 UTC, bharathkkb commented
@jmymy It may have been a flake since it was for a different test `verify beta-cluster-local`
```
     ×  Command: `gcloud beta --project=PROJECT_ID container clusters --zone=us-central1 describe simple-regional-beta-cluster-i8nk --format=json` cluster has the expected identityServiceConfig config
     
     expected: {"enabled"=>true}
          got: nil
     
     (compared using ==)
```

2022-02-15 03:46 UTC, jmymy commented
> @jmymy It may have been a flake since it was for a different test `verify beta-cluster-local`
> 
> ```
>      ×  Command: `gcloud beta --project=PROJECT_ID container clusters --zone=us-central1 describe simple-regional-beta-cluster-i8nk --format=json` cluster has the expected identityServiceConfig config
>      
>      expected: {"enabled"=>true}
>           got: nil
>      
>      (compared using ==)
> ```

nope that one was me. I found an issue with the merge/rebase and the new identity config.. Should be fixed.

2022-02-17 01:31 UTC, jmymy commented
@bharathkkb next steps? I figured i'd give @cmcga1125 more time while ya'll review the PR.

2022-02-17 21:51 UTC, bharathkkb requested changes
Thanks for working on this @jmymy 
/cc @kaariger since you worked on the KRM autopilot blueprint

2022-02-17 21:51 UTC, bharathkkb commented on examples/simple_autopilot_private/README.md
> +# Simple Regional Cluster
nit
```suggestion
# Simple Regional Autopilot Cluster
```

2022-02-17 21:51 UTC, bharathkkb commented on examples/simple_autopilot_private/README.md
> +This example illustrates how to create a simple cluster with beta features.
```suggestion
This example illustrates how to create a simple autopilot cluster with beta features.
```

2022-02-17 21:51 UTC, bharathkkb commented on examples/simple_autopilot_private/variables.tf
> +
We are now trying to hardcode these values in examples as much as possible. So lets remove variables wherever possible

2022-02-17 21:51 UTC, bharathkkb commented on examples/simple_autopilot_private/variables.tf
> +}
We shouldnt need this

2022-02-17 21:51 UTC, bharathkkb commented on examples/simple_autopilot_private/variables.tf
> +}
Some of these are not used

2022-02-17 21:51 UTC, bharathkkb commented on modules/beta-autopilot-public-cluster/versions.tf
> + * Copyright 2018 Google LLC
Here and throughout
```suggestion
 * Copyright 2022 Google LLC
```

2022-02-17 21:51 UTC, bharathkkb commented on examples/simple_autopilot_private/main.tf
> +  name                            = "${local.cluster_type}-cluster${var.cluster_name_suffix}"
```suggestion
  name                            = "simple-autopilot-private-cluster${var.cluster_name_suffix}"
```

2022-02-17 21:51 UTC, bharathkkb commented on examples/simple_autopilot_private/main.tf
> +}
Can we create the network in the same example config? We are trying to make examples more standalone and move aways from fixtures https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/930ad85d57e4207360d0833b1b42c8c978d546a4/examples/safer_cluster/network.tf

2022-02-17 21:51 UTC, bharathkkb commented on examples/simple_autopilot_private/outputs.tf
> +}
Lets not output client token unless we are using it in our test. This creates a permadiff for users trying out the example.

2022-02-21 04:46 UTC, cmcga1125 commented
> @cmcga1125 can you sign the CLA? If you want credit on the PR. Otherwise I'll have to remove your commits from the PR.

Yeah, let me figure out how to do that in the morning

2022-02-23 03:20 UTC, jmymy commented
@bharathkkb how do y'all normally handle the version file in `./test/setup` ? its causing the error above.

2022-02-24 04:36 UTC, bharathkkb commented
@jmymy I noticed it when working on another PR. You can switch to the registry source https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/99e8f9b88eff8363eb7a06faff79e460c049ac35/test/setup/main.tf

2022-03-01 02:23 UTC, jmymy commented
@bharathkkb next steps? Trying to not let this get stale

2022-03-01 18:39 UTC, morgante commented
Tests are failing. Please fix integration tests:
```
$$$$$$ Selecting the kitchen-terraform-simple-autopilot-private-local Terraform workspace...
$$$$$$ Finished selecting the kitchen-terraform-simple-autopilot-private-local Terraform workspace.
$$$$$$ Downloading the modules needed for the Terraform configuration...
       - example in ../../../examples/simple_autopilot_private
       Downloading terraform-google-modules/network/google 4.1.0 for example.gcp-network...
       - example.gcp-network in .terraform/modules/example.gcp-network
       - example.gcp-network.firewall_rules in .terraform/modules/example.gcp-network/modules/firewall-rules
       - example.gcp-network.routes in .terraform/modules/example.gcp-network/modules/routes
       - example.gcp-network.subnets in .terraform/modules/example.gcp-network/modules/subnets
       - example.gcp-network.vpc in .terraform/modules/example.gcp-network/modules/vpc
       - example.gke in ../../../modules/beta-autopilot-private-cluster
       Downloading terraform-google-modules/gcloud/google 3.1.0 for example.gke.gcloud_delete_default_kube_dns_configmap...
       - example.gke.gcloud_delete_default_kube_dns_configmap in .terraform/modules/example.gke.gcloud_delete_default_kube_dns_configmap/modules/kubectl-wrapper
       - example.gke.gcloud_delete_default_kube_dns_configmap.gcloud_kubectl in .terraform/modules/example.gke.gcloud_delete_default_kube_dns_configmap
$$$$$$ Finished downloading the modules needed for the Terraform configuration.
$$$$$$ Validating the Terraform configuration files...
       Success! The configuration is valid.
       
$$$$$$ Finished validating the Terraform configuration files.
$$$$$$ Building the infrastructure based on the Terraform configuration...
       
       Error: Invalid for_each argument
       
         on .terraform/modules/example.gcp-network/modules/subnets/main.tf line 29, in resource "google_compute_subnetwork" "subnetwork":
         29:   for_each                 = local.subnets
           ├────────────────
           │ local.subnets will be known only after apply
       
       The "for_each" value depends on resource attributes that cannot be determined
       until apply, so Terraform cannot predict how many instances will be created.
       To work around this, use the -target argument to first apply only the
 ```

2022-03-02 19:09 UTC, bharathkkb approved these changes
Unrelated tests are failing due to flakes

2022-03-02 19:10 UTC, merged