feat(cluster.tf): add support to set initial release channel version
terraform-google-modules/terraform-google-kubernetes-engine pull request #1625
Opened 2023-05-01 18:54 UTC by slimatic

This change adds support for specifying an initial version to use when a release channel is being used. The new logic sets the `min_master_version` variable to the value of the locally defined `master_version` when `release_channel` is `null` or `"UNSPECIFIED"`. When a release channel is specified, `min_master_version` is set to the value of `initial_version` if it is defined, and falls back to the value of `master_version` otherwise.

2023-05-01 19:06 UTC, apeabody commented
/gcbrun

2023-05-09 18:45 UTC, apeabody commented
/gcbrun

2023-05-09 18:52 UTC, apeabody requested changes
Thanks for the contribution @slimatic!

If we don't have one already, please include one of the test fixtures setting `kubernetes_version = "latest"` so this new functionally is covered by the Integration tests.

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/test/fixtures

2023-05-09 18:52 UTC, apeabody commented on cluster.tf
> +  min_master_version = var.release_channel == null || var.release_channel == "UNSPECIFIED" ? local.master_version : var.kubernetes_version == null ? null : var.kubernetes_version
Was this intended to be`null`?

```suggestion
  min_master_version = var.release_channel == null || var.release_channel == "UNSPECIFIED" ? local.master_version : var.kubernetes_version == "latest" ? null : var.kubernetes_version
```

2023-05-12 20:27 UTC, apeabody commented
/gcbrun

2023-05-12 20:42 UTC, apeabody commented
/gcbrun

2023-05-12 21:11 UTC, slimatic commented
> /gcbrun

@apeabody fixed the tests and addressed the lint failures.

2023-05-12 21:30 UTC, apeabody commented
/gcbrun

2023-05-12 22:14 UTC, slimatic commented
> /gcbrun

@apeabody applied `make build` changes to README.md

2023-05-12 22:28 UTC, apeabody commented
/gcbrun

2023-05-12 22:40 UTC, apeabody commented
/gcbrun

2023-05-16 15:39 UTC, apeabody commented
/gcbrun

2023-05-16 16:09 UTC, slimatic commented
@apeabody I noticed the cicd build is failing. Is my attention required on the failure? Please advise.

2023-05-16 16:56 UTC, apeabody commented
> @apeabody I noticed the cicd build is failing. Is my attention required on the failure? Please advise.

I think it's unrelated, hopefully resolved by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1637

2023-05-16 19:44 UTC, apeabody commented
/gcbrun

2023-05-16 23:46 UTC, apeabody commented
/gcbrun

2023-05-19 13:58 UTC, slimatic commented
> Thanks for the contribution @slimatic!
> 
> If we don't have one already, please include one of the test fixtures setting `kubernetes_version = "latest"` so this new functionally is covered by the Integration tests.
> 
> https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/test/fixtures

@apeabody the requested change has been added.

2023-05-19 14:01 UTC, slimatic commented
> > Thanks for the contribution @slimatic!
> > If we don't have one already, please include one of the test fixtures setting `kubernetes_version = "latest"` so this new functionally is covered by the Integration tests.
> > https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/test/fixtures
> 
> @apeabody the requested change has been added.

@apeabody apologies, I accidentally closed the PR when I was commenting.

2023-05-19 15:23 UTC, apeabody commented
/gcbrun

2023-05-22 20:50 UTC, slimatic commented
@apeabody just triggered a new merge of the master branch.
could you also advise on what is needed to successfully merge the pull request?

2023-05-22 20:56 UTC, apeabody commented
> @apeabody just triggered a new merge of the master branch. could you also advise on what is needed to successfully merge the pull request?

Thanks @slimatic, I'll re-run the CI.  Per merge timeline, what are the potential impacts to existing clusters?  Just need to determine if this is OK for immediate minor release now, or if it will need to be a major release with migration documentation.

2023-05-22 20:57 UTC, apeabody commented
/gcbrun

2023-05-22 21:49 UTC, slimatic commented
> > @apeabody just triggered a new merge of the master branch. could you also advise on what is needed to successfully merge the pull request?
> 
> Thanks @slimatic, I'll re-run the CI. Per merge timeline, what are the potential impacts to existing clusters? Just need to determine if this is OK for immediate minor release now, or if it will need to be a major release with migration documentation.

@apeabody Thanks for providing some insight on the merge timelines.

2023-05-30 14:15 UTC, slimatic commented
> 



> > @apeabody just triggered a new merge of the master branch. could you also advise on what is needed to successfully merge the pull request?
> 
> Thanks @slimatic, I'll re-run the CI. Per merge timeline, what are the potential impacts to existing clusters? Just need to determine if this is OK for immediate minor release now, or if it will need to be a major release with migration documentation.


@apeabody were the following questions were directed to me? 
- "Per merge timeline, what are the potential impacts to existing clusters? "
-  "OK for immediate minor release now, or if it will need to be a major release "

2023-05-30 16:14 UTC, apeabody commented
Hi @slimatic - Thanks, yes, do you have any insight on the potential impacts to existing clusters?

2023-05-30 16:14 UTC, apeabody commented
/gcbrun

2023-05-30 20:03 UTC, slimatic commented
> Hi @slimatic - Thanks, yes, do you have any insight on the potential impacts to existing clusters?

Yes, based on my tests, making this change will have minimal impact on existing clusters. If the Kubernetes version is modified and applied to an existing cluster, Terraform will upgrade the cluster only if the specified version is greater than the current version. If the version is smaller than the existing version, the terraform apply command will complete successfully without upgrading the cluster version.

2023-06-02 00:23 UTC, bharathkkb approved these changes
Thanks @slimatic and @apeabody. I did a quick test to validate and observed similar behavior as noted by @slimatic so it looks okay to release as minor.

2023-06-02 03:22 UTC, apeabody commented
> Thanks @slimatic and @apeabody. I did a quick test to validate and observed similar behavior as noted by @slimatic so it looks okay to release as minor.

Thanks @bharathkkb - That was above and beyond!

2023-06-02 03:22 UTC, apeabody approved these changes

2023-06-02 16:04 UTC, apeabody commented
/gcbrun

2023-06-02 16:04 UTC, apeabody commented
Will merge once the CI is all green.

2023-06-02 16:59 UTC, merged