feat: Create least privilege default service account #1416
terraform-google-modules/terraform-google-kubernetes-engine pull request #1757
Opened 2023-10-02 08:27 UTC by abhikaddy

Attempting to fix #1416

2023-10-02 15:27 UTC, apeabody commented
/gcbrun

2023-10-05 21:58 UTC, abhikaddy commented
@Jberlinsky @ericyz

2023-10-19 13:31 UTC, abhikaddy commented
@apeabody  Can I get what failed in the cloud build check?

2023-10-19 15:43 UTC, apeabody commented
/gcbrun

2023-10-20 00:10 UTC, apeabody commented
> @apeabody Can I get what failed in the cloud build check?

re-triggered the check

2023-10-21 09:39 UTC, abhikaddy commented
Hi Good Day!
Can I get a merge? @apeabody @ericyz @Jberlinsky

2023-10-23 21:02 UTC, apeabody requested changes
Thanks for the contribution @abhikaddy!

As this permissions reduction could be a breaking change for some users, can you please add a quick update note regarding the change to `docs/upgrading_to_v29.0.md`, similar to those in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs

2023-10-25 09:22 UTC, abhikaddy commented
Hi @apeabody,

As requested, added docs/upgrading_to_v29.0.md. 
Requesting a review.

Thanks.

2023-10-25 15:00 UTC, apeabody commented
/gcbrun

2023-10-25 15:34 UTC, apeabody commented on docs/upgrading_to_v29.0.md
> +This is the Google recommended least privileged role to be used for the service account attached to the GKE Nodes.
```suggestion
This is the Google recommended least privileged role to be used for the service account attached to the GKE Nodes.

```

2023-10-25 17:55 UTC, apeabody commented
/gcbrun

2023-10-25 19:47 UTC, apeabody commented
/gcbrun

2023-10-26 22:34 UTC, apeabody approved these changes

2023-10-26 22:34 UTC, merged

2023-12-14 00:35 UTC, shinebayar-g commented
Are we supposed to create `roles/container.nodeServiceAccount` by ourselves? This role doesn't exist.

2023-12-21 16:09 UTC, legal90 commented
That role exists, but it's not visible in GCP Console. It seems that it was deprecated (and hidden?). 
gcloud CLI output confirms that:
```
$ gcloud iam roles describe roles/container.nodeServiceAccount
description: Least privilege role to use as the service account for GKE Nodes.
etag: AA==
includedPermissions:
- autoscaling.sites.writeMetrics
- logging.logEntries.create
- monitoring.metricDescriptors.create
- monitoring.metricDescriptors.list
- monitoring.timeSeries.create
- monitoring.timeSeries.list
- resourcemanager.projects.get
- resourcemanager.projects.list
- serviceusage.services.use
- storage.objects.get
- storage.objects.list
name: roles/container.nodeServiceAccount
stage: DEPRECATED                                   # <===
title: Kubernetes Engine Node Service Account
```

This role is also not mentioned here: 
cc @apeabody . Should that PR be reverted?

P.s.
In my case I had to disable the SA creation (`create_service_account = false`) and created it outside of the module instead, as well as create bindings to `roles/logging.logWriter, `roles/monitoring.metricWriter`.

2023-12-21 18:03 UTC, apeabody commented
Opened https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1827

2024-01-12 15:27 UTC, gorge511 commented
There is a new role named `roles/container.nodeServiceAgent` which should be used instead of deprecated `roles/container.nodeServiceAccount`. Should we migrate to this role instead of reverting the change? Or is there some other reason for revert which I'm not aware of?

```yaml
$ gcloud iam roles describe roles/container.nodeServiceAgent  
description: Minimal set of permission required by a GKE node to support standard
  capabilities such as logging and monitoring export, and image pulls.
etag: AA==
includedPermissions:
- autoscaling.sites.writeMetrics
- logging.logEntries.create
- monitoring.metricDescriptors.create
- monitoring.metricDescriptors.list
- monitoring.timeSeries.create
- monitoring.timeSeries.list
- resourcemanager.projects.get
- resourcemanager.projects.list
- serviceusage.services.use
- storage.objects.get
- storage.objects.list
name: roles/container.nodeServiceAgent
stage: GA
title: Kubernetes Engine Node Service Agent
```

2024-01-12 15:33 UTC, shinebayar-g commented
Is there any source that I can refer to? I thought service agent type of iam service accounts are created by GCP used internally only.

2024-01-12 16:35 UTC, legal90 commented
@shinebayar-g You are right.  Service **Agent** roles should not be greanted to any principal except service agents:

> Warning: Do not grant service agent roles to any principals except service agents. Some service agent roles contain very powerful permissions, and the permissions within these roles can change without notice. Instead, choose a different [predefined role](https://cloud.google.com/iam/docs/understanding-roles#predefined_roles), or create a [custom role](https://cloud.google.com/iam/docs/understanding-custom-roles) with the permissions you need.

https://cloud.google.com/iam/docs/service-agents

2024-01-12 16:45 UTC, gorge511 commented
Ok, you are both right. Agent roles should be used only for Agents, which in this case is probably just Autopilot node agent account.

I just got a message from Google representative that there is currently running effort updating this recommendation and there is new `roles/container.defaultNodeServiceAccount` currently in ALPHA stage which should replace the old one.

The list of permissions is shorter than in the old role, so I'm little bit scared of using it 🙂 

```yaml
$ gcloud iam roles describe roles/container.defaultNodeServiceAccount
description: Least privilege role to use as the default service account for GKE Nodes.
etag: AA==
includedPermissions:
- autoscaling.sites.writeMetrics
- logging.logEntries.create
- monitoring.metricDescriptors.create
- monitoring.metricDescriptors.list
- monitoring.timeSeries.create
- monitoring.timeSeries.list
- stackdriver.resourceMetadata.write
name: roles/container.defaultNodeServiceAccount
stage: ALPHA
title: Kubernetes Engine Default Node Service Account
```

Also I came across another [docs page](https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#use_least_privilege_sa) which is suggesting usage of 5 different roles.

So I'm confused now 😕

2024-01-12 18:48 UTC, shinebayar-g commented
Yes. I was also soooo confused. Because there are so many duplicate docs saying different things.

2024-01-13 12:17 UTC, gorge511 commented
I received confirmation from Google representative that the new role should be ok to use, so I prepared #1844.
> I've asked Engineering for clarification and recommendation about new role - it is good to go and use

2024-02-15 20:56 UTC, NeckBeardPrince commented
Maybe I'm an outlier here, but anybody else feel a little uneasy switching to a new SA? That's currently, in ALPHA, and there is zero documentation on the new role? Perhaps, we shouldn't switch to using new roles that are still in ALPHA?

2024-03-12 03:45 UTC, hSATAC commented
Is there any downtime for the SA recreation for existing clusters? I simply want to upgrade the google provider...

2024-03-12 14:29 UTC, NeckBeardPrince commented
> Is there any downtime for the SA recreation for existing clusters? I simply want to upgrade the google provider...

No downtime.