fix: :bug: enable/disable observability inputs & `logmon_config_is_set`
terraform-google-modules/terraform-google-kubernetes-engine pull request #1894
Opened 2024-03-04 22:44 UTC by Markieta

- Adds `monitoring_enable_observability_relay` as per [google_container_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enable_relay).
- Change `logmon_config_is_set` to check for _observability_ inputs as well.
- Sets the following inputs to `null` instead of `false` to support disabling existing pre-enabled features via Terraform:
  - `monitoring_enable_managed_prometheus`
  - `monitoring_enable_observability_metrics`
  - `monitoring_enable_observability_relay`

2024-03-14 04:20 UTC, bharathkkb commented
/gcbrun

2024-03-29 17:27 UTC, matthisholleville commented
Can't wait to use this PR !!

2024-05-30 15:32 UTC, apeabody requested changes
Thanks for the contribution @Markieta!

Can you please rebase the PR, and we'll do a fresh run of the CI tests.

2024-05-30 16:58 UTC, Markieta commented
Hope my commits struggling to rebase/merge is not a problem. :sweat_smile:

Should be good to test now.

2024-05-30 18:11 UTC, apeabody commented
> Hope my commits struggling to rebase/merge is not a problem. 😅
> 
> Should be good to test now.

No problem at all, we squash into a single commit on merge.

2024-05-30 18:33 UTC, apeabody commented
From the CI tests:

```
TestBetaCluster 2024-05-30T18:32:07Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; 
Error: Missing required argument

  with module.this.module.gke.google_container_cluster.primary,
  on ../../../modules/beta-public-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {

The argument
"monitoring_config.0.advanced_datapath_observability_config.0.enable_metrics"
is required, but no definition was found.}
```

2024-06-22 01:01 UTC, apeabody commented
/gcbrun

2024-06-25 18:24 UTC, apeabody commented
From the test:

```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Missing required argument
        	            	
        	            	  with module.example.module.gke.google_container_cluster.primary,
        	            	  on ../../../modules/beta-public-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
        	            	  22: resource "google_container_cluster" "primary" {
        	            	
        	            	The argument
        	            	"monitoring_config.0.advanced_datapath_observability_config.0.enable_metrics"
        	            	is required, but no definition was found.}
        	Test:       	TestSandboxEnabled
```

2024-08-26 00:52 UTC, awx-fuyuanchu commented
bump

2024-09-04 22:34 UTC, slimatic commented
can this be bumped?

2024-11-07 13:56 UTC, awx-fuyuanchu commented
bump

2025-02-26 23:04 UTC, closed without merging