feat: add secret manager add-on config to beta modules
terraform-google-modules/terraform-google-kubernetes-engine pull request #1977
Opened 2024-06-14 09:34 UTC by legal90

This PR adds a new variable to all beta-* modules allowing to enable Secret Manager add-on for GKE:
- https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enabled

2024-06-14 15:51 UTC, apeabody commented
/gcbrun

2024-06-20 19:00 UTC, apeabody commented
Hi @legal90 - Can you please rebase?

2024-06-21 07:55 UTC, legal90 commented
@apeabody Sure! Rebased now

2024-06-21 15:45 UTC, apeabody commented
/gcbrun

2024-06-21 20:43 UTC, apeabody requested changes
Thanks for the contribution @legal90

Looks like this was added in v5.33.0, so please bump here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/main/versions.tf.tmpl

2024-06-22 12:43 UTC, legal90 commented
Thank you, good point!  I bumped the min version now.

2024-06-24 15:45 UTC, apeabody commented
/gcbrun

2024-06-26 15:10 UTC, apeabody commented
/gcbrun

2024-06-28 15:43 UTC, apeabody commented
/gcbrun

2024-07-01 16:20 UTC, apeabody approved these changes

2024-07-02 15:53 UTC, apeabody commented
Hi @legal90 - Can you please merge in changes from the base branch.  Thanks!

2024-07-08 12:26 UTC, legal90 commented
@apeabody Sure! Rebased the branch now.

2024-07-08 17:51 UTC, apeabody commented
/gcbrun

2024-07-08 20:34 UTC, apeabody approved these changes
Thanks for the contribution @legal90!

2024-07-08 20:35 UTC, apeabody commented
Hi @legal90 - Can you please rebase, I'm not able to update your PRs.  Once it is current, and the checks are green, it's ready to merge.

2024-07-09 17:54 UTC, apeabody commented
/gcbrun

2024-07-09 19:00 UTC, merged