Add additional functionality for autopilot clusters
terraform-google-modules/terraform-google-kubernetes-engine pull request #1985
Opened 2024-07-02 21:36 UTC by kliu47

Additionally GA functionality for GKE autopilot modules:

- [GCS Fuse addition](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver)
- [Bakeup for GKE](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/concepts/backup-for-gke)
  - [Autopilot Support](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/concepts/about-autopilot)
- [Stateful HA Operator](https://cloud.google.com/kubernetes-engine/docs/how-to/stateful-ha)

2024-07-02 21:40 UTC, kliu47 commented
Updated the test in simple_autopilot_public as an example of enabling gcs_fuse

2024-07-02 23:33 UTC, apeabody requested changes
Thanks for the contribution @kliu47!

I've noted some initial feedback on whitespace and triggered the CI tests.

/gcbrun

2024-07-02 23:33 UTC, apeabody commented on autogen/main/cluster.tf.tmpl
> +
Let's minimize the white space

```suggestion
```

2024-07-02 23:33 UTC, apeabody commented on autogen/main/cluster.tf.tmpl
> +
```suggestion
```

2024-07-02 23:33 UTC, apeabody commented on autogen/main/cluster.tf.tmpl
>      {% if beta_cluster and autopilot_cluster != true %}
Let's add one whitespace back

```suggestion

    {% if beta_cluster and autopilot_cluster != true %}
```

2024-07-02 23:33 UTC, apeabody commented on autogen/main/variables.tf.tmpl
> +
```suggestion
```

2024-07-02 23:34 UTC, apeabody commented
/gcbrun

2024-07-03 03:31 UTC, kliu47 commented on autogen/main/cluster.tf.tmpl
>      {% if beta_cluster and autopilot_cluster != true %}
Fixed

2024-07-03 03:32 UTC, kliu47 commented on autogen/main/variables.tf.tmpl
> +
Fixed

2024-07-03 03:32 UTC, kliu47 commented on autogen/main/cluster.tf.tmpl
> +
Fixed

2024-07-03 15:08 UTC, apeabody commented
/gcbrun

2024-07-03 15:09 UTC, apeabody commented
From the linter:

```
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/instance_template/README.md /tmp/tmp.WhX65XKh44/workspace/modules/instance_template/README.md
23c23
< | description | The template's description | `""` |`string` | no |
---
> | description | The template's description | `string` | `""` | no |
33c33
< | instance\_description | Description of the generated instances | `""` | `string` | no |
---
> | instance\_description | Description of the generated instances | `string` | `""` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
/usr/local/bin/task_helper_functions.sh: line 30: DELETE_AT_EXIT: readonly variable
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/modules/instance_template/README.md /tmp/tmp.IrquMowoNu/generate_docs/workspace/modules/instance_template/README.md
23c23
< | description | The template's description | `""` |`string` | no |
---
> | description | The template's description | `string` | `""` | no |
33c33
< | instance\_description | Description of the generated instances | `""` | `string` | no |
---
> | instance\_description | Description of the generated instances | `string` | `""` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
```

2024-07-04 01:12 UTC, kliu47 commented
Weird that the linter is asking me to re-run make build and make generate docs. Tried both and VCS is showing no changes to commit.

2024-07-08 18:04 UTC, apeabody commented
> Weird that the linter is asking me to re-run make build and make generate docs. Tried both and VCS is showing no changes to commit.

Interesting, I don't think your PR should impact those lines.  Re-running

/gcbrun

2024-07-08 21:17 UTC, apeabody approved these changes
Thanks for the contribution @kliu47!

2024-07-08 21:18 UTC, merged