feat: bump identity_service_config to ga
terraform-google-modules/terraform-google-kubernetes-engine pull request #1997
Opened 2024-07-16 20:14 UTC by DrFaust92

2024-07-16 23:02 UTC, apeabody commented
/gcbrun

2024-07-17 20:33 UTC, apeabody commented
/gcbrun

2024-07-18 16:56 UTC, apeabody requested changes
Thanks for the contribution @DrFaust92!

2024-07-18 19:23 UTC, DrFaust92 commented
fixing the lint error

2024-07-18 19:36 UTC, apeabody commented
/gcbrun

2024-07-18 21:22 UTC, apeabody approved these changes
Thanks for the contribution @DrFaust92!

2024-07-18 21:24 UTC, merged