feat: allow default node pools metadata key-value pairs to be disabled
terraform-google-modules/terraform-google-kubernetes-engine pull request #2005
Opened 2024-07-23 21:49 UTC by caueasantos

Resolves #2004 

There are many ways to go about this, but I tried to quickly expose a way for users to disable default metadata labels added by the module.

First time opening a pull request here, let me know I missed anything.

2024-07-24 20:34 UTC, apeabody requested changes
Thanks for the contribution @caueasantos!

Should this change apply to Autopilot cluster?

```
Working in ./modules/beta-autopilot-private-cluster ...
1 issue(s) found:

Warning: [Fixable] variable "enable_default_node_pools_metadata" is declared but not used (terraform_unused_declarations)

  on variables.tf line 427:
 427: variable "enable_default_node_pools_metadata" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.7.0/docs/rules/terraform_unused_declarations.md

tflint failed ./modules/beta-autopilot-private-cluster 
Working in ./modules/beta-autopilot-public-cluster ...
1 issue(s) found:

Warning: [Fixable] variable "enable_default_node_pools_metadata" is declared but not used (terraform_unused_declarations)

  on variables.tf line 397:
 397: variable "enable_default_node_pools_metadata" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.7.0/docs/rules/terraform_unused_declarations.md

tflint failed ./modules/beta-autopilot-public-cluster 
```

2024-07-25 14:35 UTC, caueasantos commented
> Thanks for the contribution @caueasantos!
> 
> Should this change apply to Autopilot cluster?
> 
> ```
> Working in ./modules/beta-autopilot-private-cluster ...
> 1 issue(s) found:
> 
> Warning: [Fixable] variable "enable_default_node_pools_metadata" is declared but not used (terraform_unused_declarations)
> 
>   on variables.tf line 427:
>  427: variable "enable_default_node_pools_metadata" {
> 
> Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.7.0/docs/rules/terraform_unused_declarations.md
> 
> tflint failed ./modules/beta-autopilot-private-cluster 
> Working in ./modules/beta-autopilot-public-cluster ...
> 1 issue(s) found:
> 
> Warning: [Fixable] variable "enable_default_node_pools_metadata" is declared but not used (terraform_unused_declarations)
> 
>   on variables.tf line 397:
>  397: variable "enable_default_node_pools_metadata" {
> 
> Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.7.0/docs/rules/terraform_unused_declarations.md
> 
> tflint failed ./modules/beta-autopilot-public-cluster 
> ```

Definitely not, let me see how I can disable the variable for autopilot clusters using the autogeneration templates.

2024-07-25 16:54 UTC, apeabody commented on autogen/main/variables.tf.tmpl
> +}
nit: let's move the line return into the block so we don't get extra spaces in autopilot_cluster != true

```suggestion
}

```

2024-07-25 16:55 UTC, apeabody commented on autogen/main/variables.tf.tmpl
> +
nit: let's move the line return into the block so we don't get extra spaces in autopilot_cluster != true

```suggestion
```

2024-07-25 16:56 UTC, apeabody commented
/gcbrun

2024-07-25 19:23 UTC, apeabody commented
/gcbrun

2024-07-26 18:56 UTC, apeabody approved these changes

2024-07-26 18:57 UTC, merged