support supworkload_identity_config on autopilot
terraform-google-modules/terraform-google-kubernetes-engine pull request #2011
Opened 2024-07-26 02:56 UTC by DrFaust92

supported via https://github.com/hashicorp/terraform-provider-google/pull/18166

2024-07-26 16:55 UTC, apeabody requested changes
Thanks for the contribution @DrFaust92!

I believe this will require bumping the minimum provider to `[5.31](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.31.0)`

2024-07-27 14:00 UTC, DrFaust92 commented
[apeabody](https://github.com/apeabody) oops, saw the ref for beta for 5.33+ and missed the GA one, bumped GA as well

2024-07-29 18:42 UTC, apeabody commented
/gcbrun

2024-07-30 16:58 UTC, apeabody commented
> [apeabody](https://github.com/apeabody) oops, saw the ref for beta for 5.33+ and missed the GA one, bumped GA as well

Thanks @DrFaust92 - Actually looks like this is only being added to the `beta` autopilot clusters?  Probably want to enable to the GA variants as well?

2024-07-31 03:12 UTC, DrFaust92 commented
[apeabody](https://github.com/apeabody) i dont see a non beta auto pilot dir at all. is that even an option?
<img width="639" alt="Screenshot 2024-07-30 at 23 12 05" src="https://github.com/user-attachments/assets/4c872270-0fc8-44c2-81d2-e4a5fcd2aa3f">

2024-07-31 18:03 UTC, apeabody commented
> [apeabody](https://github.com/apeabody) i dont see a non beta auto pilot dir at all. is that even an option? <img alt="Screenshot 2024-07-30 at 23 12 05" width="639" src="https://private-user-images.githubusercontent.com/33663870/353677775-4c872270-0fc8-44c2-81d2-e4a5fcd2aa3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDkxNTYsIm5iZiI6MTcyMjQ0ODg1NiwicGF0aCI6Ii8zMzY2Mzg3MC8zNTM2Nzc3NzUtNGM4NzIyNzAtMGZjOC00NGMyLTgxZDItZTRhNWZjZDJhYTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE4MDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZWYxYzM4NTQ3YTVlNThlZjgyNjliNWY3ZDg5Mjg3OTE3NDdhMDRjM2Y1MzY4ZTg3ZmUwYzk4NTBlODZhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oOljPQ_FOfV00MwkcSfdqUDkOy2iQgi0z2o3JxDVGwQ">

You are correct @DrFaust92, I saw the updates to the over module's `version.tf`, but didn't check that they weren't Autopilot clusters.  If we don't have a non-beta Autopilot clusters, we can actually revert https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2011/files#diff-5ccc4bcabc51d0aa62a45f4a5cfe9868fb5f29fc613afa1f5a16e5c263b16d99L49, and then this should be ready to commit.  Thanks!

2024-07-31 18:04 UTC, apeabody commented on autogen/main/versions.tf.tmpl
> +      version = ">= 5.31.0, < 6"
@DrFaust92 - Let's revert and build, and then this should be ready to merge.

2024-07-31 23:32 UTC, apeabody commented
/gcbrun

2024-07-31 23:32 UTC, apeabody approved these changes

2024-08-01 18:50 UTC, apeabody commented
/gcbrun

2024-08-01 19:57 UTC, merged