correct confidential node field name
terraform-google-modules/terraform-google-kubernetes-engine pull request #2140
Opened 2024-10-16 21:03 UTC by redoak666

The field name confidential_node in dynamic block confidential_nodes at nodepool level is incorrect, it should be enabled_confidential_nodes  
dynamic "confidential_nodes" {
      for_each = lookup(each.value, "enable_confidential_nodes", null) != null ? [each.value.confidential_nodes] : []
      content {
        enabled = confidential_nodes.value
}

2024-10-16 21:20 UTC, apeabody commented
/gcbrun

2024-10-16 21:26 UTC, apeabody requested changes
Thanks for the contribution @redoak666!

Can you please update the template as noted here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CONTRIBUTING.md#templating

2024-10-16 22:53 UTC, redoak666 commented
@apeabody
updated per instruction

2024-10-16 22:59 UTC, apeabody commented
/gcbrun

2024-10-16 23:13 UTC, apeabody approved these changes

2024-10-17 00:10 UTC, apeabody approved these changes
Thanks for the contribution @redoak666!

2024-10-17 00:10 UTC, merged