feat: add cgroup & sysctls to safe-cluster & safe-cluster-update-variant
terraform-google-modules/terraform-google-kubernetes-engine pull request #2214
Opened 2024-12-13 17:48 UTC by j

2024-12-13 18:10 UTC, apeabody requested changes
Thanks for the contribution @j!

Can you please update the template(s) and regenerate the resulting docs.  Thanks!

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CONTRIBUTING.md#templating

2024-12-16 22:54 UTC, j commented
@apeabody pushed!

2024-12-16 23:14 UTC, apeabody commented
/gcbrun

2024-12-18 00:30 UTC, apeabody commented
/gcbrun

2024-12-20 18:46 UTC, apeabody commented
Hi @j - Thanks again for the contribution!

I've discussed this proposed change with the larger team, and the decision is to instead recommend using the `beta-private-cluster` or `beta-private-cluster-update-variant` modules.  The purpose of the Safer Cluster modules are to only present a limited set of parameters in-line with the [GKE hardening guide](https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster), the CIS framework, and other best practices.  The `beta-private-cluster` or `beta-private-cluster-update-variant` modules provide the full range of parameters, and can also be configured in the same fashion as the Safer Cluster modules as needed.

Best Wishes!

2025-02-03 17:08 UTC, closed without merging