feat: add support for hugepages_config + fix setting cgroup_name via "all""
terraform-google-modules/terraform-google-kubernetes-engine pull request #2223
Opened 2024-12-21 18:18 UTC by DrFaust92

2024-12-23 17:44 UTC, apeabody commented
/gcbrun

2024-12-24 00:20 UTC, apeabody requested changes
Thanks for the contribution @DrFaust92!

Can you please add to an example for test coverage, otherwise other than some extra spaces, this LGTM.



NOTE: `hugepages_config` added in [v6.5.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.5.0)

2024-12-24 00:20 UTC, apeabody commented on autogen/main/cluster.tf.tmpl
> +            hugepage_size_2m = coalesce(local.node_pools_hugepage_size_2m[each.value["name"]], local.node_pools_hugepage_size_2m["all"])  == "" ? null : coalesce(local.node_pools_hugepage_size_2m[eac
nit

```suggestion
            hugepage_size_2m = coalesce(local.node_pools_hugepage_size_2m[each.value["name"]], local.node_pools_hugepage_size_2m["all"]) == "" ? null : coalesce(local.node_pools_hugepage_size_2m[each.value["name"]], local.node_pools_hugepage_size_2m["all"])
```

2024-12-24 00:20 UTC, apeabody commented on autogen/main/cluster.tf.tmpl
> +            hugepage_size_2m = coalesce(local.node_pools_hugepage_size_2m[each.value["name"]], local.node_pools_hugepage_size_2m["all"])  == "" ? null : coalesce(local.node_pools_hugepage_size_2m[eac
nit

```suggestion
            hugepage_size_2m = coalesce(local.node_pools_hugepage_size_2m[each.value["name"]], local.node_pools_hugepage_size_2m["all"]) == "" ? null : coalesce(local.node_pools_hugepage_size_2m[each.value["name"]], local.node_pools_hugepage_size_2m["all"])
```

2025-01-02 20:01 UTC, DrFaust92 commented
@apeabody Tried my best with tests here as well 😊 . LMK if something needs fixing

2025-01-02 23:14 UTC, apeabody commented
/gcbrun

2025-01-02 23:49 UTC, apeabody commented
FYI @DrFaust92 - A few of the pools do use `n1`, but the rest are currently `e2`.

```
TestNodePool 2025-01-02T23:41:57Z command.go:185: Error: error creating NodePool: googleapi: Error 400: 1G hugepages was set but the nodepool machine type(e2-medium) does not support this configuration.
TestNodePool 2025-01-02T23:41:57Z command.go:185: Details:
TestNodePool 2025-01-02T23:41:57Z command.go:185: [
TestNodePool 2025-01-02T23:41:57Z command.go:185:   {
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "@type": "type.googleapis.com/google.rpc.RequestInfo",
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "requestId": "0x7b26367c30d761e2"
TestNodePool 2025-01-02T23:41:57Z command.go:185:   }
TestNodePool 2025-01-02T23:41:57Z command.go:185: ]
TestNodePool 2025-01-02T23:41:57Z command.go:185: , badRequest
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185:   with module.example.module.gke.google_container_node_pool.pools["pool-04"],
TestNodePool 2025-01-02T23:41:57Z command.go:185:   on ../../../modules/beta-public-cluster/cluster.tf line 597, in resource "google_container_node_pool" "pools":
TestNodePool 2025-01-02T23:41:57Z command.go:185:  597: resource "google_container_node_pool" "pools" {
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185: Error: error creating NodePool: googleapi: Error 400: 1G hugepages was set but the nodepool machine type(e2-medium) does not support this configuration.
TestNodePool 2025-01-02T23:41:57Z command.go:185: Details:
TestNodePool 2025-01-02T23:41:57Z command.go:185: [
TestNodePool 2025-01-02T23:41:57Z command.go:185:   {
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "@type": "type.googleapis.com/google.rpc.RequestInfo",
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "requestId": "0x48e2d757411a4297"
TestNodePool 2025-01-02T23:41:57Z command.go:185:   }
TestNodePool 2025-01-02T23:41:57Z command.go:185: ]
TestNodePool 2025-01-02T23:41:57Z command.go:185: , badRequest
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185:   with module.example.module.gke.google_container_node_pool.pools["pool-01"],
TestNodePool 2025-01-02T23:41:57Z command.go:185:   on ../../../modules/beta-public-cluster/cluster.tf line 597, in resource "google_container_node_pool" "pools":
TestNodePool 2025-01-02T23:41:57Z command.go:185:  597: resource "google_container_node_pool" "pools" {
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185: Error: error creating NodePool: googleapi: Error 400: 1G hugepages was set but the nodepool machine type(n1-standard-2) does not support this configuration.
TestNodePool 2025-01-02T23:41:57Z command.go:185: Details:
TestNodePool 2025-01-02T23:41:57Z command.go:185: [
TestNodePool 2025-01-02T23:41:57Z command.go:185:   {
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "@type": "type.googleapis.com/google.rpc.RequestInfo",
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "requestId": "0x16e561c8b65549ca"
TestNodePool 2025-01-02T23:41:57Z command.go:185:   }
TestNodePool 2025-01-02T23:41:57Z command.go:185: ]
TestNodePool 2025-01-02T23:41:57Z command.go:185: , badRequest
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185:   with module.example.module.gke.google_container_node_pool.pools["pool-03"],
TestNodePool 2025-01-02T23:41:57Z command.go:185:   on ../../../modules/beta-public-cluster/cluster.tf line 597, in resource "google_container_node_pool" "pools":
TestNodePool 2025-01-02T23:41:57Z command.go:185:  597: resource "google_container_node_pool" "pools" {
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185: Error: error creating NodePool: googleapi: Error 400: 1G hugepages was set but the nodepool machine type(n1-standard-2) does not support this configuration.
TestNodePool 2025-01-02T23:41:57Z command.go:185: Details:
TestNodePool 2025-01-02T23:41:57Z command.go:185: [
TestNodePool 2025-01-02T23:41:57Z command.go:185:   {
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "@type": "type.googleapis.com/google.rpc.RequestInfo",
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "requestId": "0x40383fdeb6fa524a"
TestNodePool 2025-01-02T23:41:57Z command.go:185:   }
TestNodePool 2025-01-02T23:41:57Z command.go:185: ]
TestNodePool 2025-01-02T23:41:57Z command.go:185: , badRequest
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185:   with module.example.module.gke.google_container_node_pool.pools["pool-05"],
TestNodePool 2025-01-02T23:41:57Z command.go:185:   on ../../../modules/beta-public-cluster/cluster.tf line 597, in resource "google_container_node_pool" "pools":
TestNodePool 2025-01-02T23:41:57Z command.go:185:  597: resource "google_container_node_pool" "pools" {
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185: Error: error creating NodePool: googleapi: Error 400: 1G hugepages was set but the nodepool machine type(n1-standard-2) does not support this configuration.
TestNodePool 2025-01-02T23:41:57Z command.go:185: Details:
TestNodePool 2025-01-02T23:41:57Z command.go:185: [
TestNodePool 2025-01-02T23:41:57Z command.go:185:   {
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "@type": "type.googleapis.com/google.rpc.RequestInfo",
TestNodePool 2025-01-02T23:41:57Z command.go:185:     "requestId": "0x37ecaeacf733a8ea"
TestNodePool 2025-01-02T23:41:57Z command.go:185:   }
TestNodePool 2025-01-02T23:41:57Z command.go:185: ]
TestNodePool 2025-01-02T23:41:57Z command.go:185: , badRequest
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z command.go:185:   with module.example.module.gke.google_container_node_pool.pools["pool-02"],
TestNodePool 2025-01-02T23:41:57Z command.go:185:   on ../../../modules/beta-public-cluster/cluster.tf line 597, in resource "google_container_node_pool" "pools":
TestNodePool 2025-01-02T23:41:57Z command.go:185:  597: resource "google_container_node_pool" "pools" {
TestNodePool 2025-01-02T23:41:57Z command.go:185: 
TestNodePool 2025-01-02T23:41:57Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; 
```

2025-01-03 00:23 UTC, DrFaust92 commented
@apeabody should i change the node pools types to support the test case? or how should I approach this?

2025-01-03 00:33 UTC, apeabody commented
> @apeabody should i change the node pools types to support the test case? or how should I approach this?


The 2-m huge pages should be fine as-is, however for the 1-g perhaps just test a single node pool which has a supported machine type.  Maybe change `"pool-05"` to `c3-standard-4`?

`1-gigabtye-sized huge pages are only available on the A3, C2D, C3, C3A, C3D, C4, CT5E, CT5L, CT5LP, CT6E, H3, M2, M3, or Z3 [machine types](https://cloud.google.com/compute/docs/machine-resource).`

2025-01-04 23:04 UTC, DrFaust92 commented
[apeabody](https://github.com/apeabody) lets try now

2025-01-06 16:24 UTC, apeabody commented
/gcbrun

2025-04-03 15:25 UTC, apeabody commented
/gcbrun

2025-04-07 03:18 UTC, DrFaust92 commented
[apeabody](https://github.com/apeabody) added try as requested

2025-04-07 17:10 UTC, rawanbadawi commented
@apeabody My customer needs this feature, is it possible to approve the latest?

Thanks

2025-04-07 17:17 UTC, apeabody commented
/gcbrun

2025-04-07 19:04 UTC, apeabody commented
INT test results:
```
        	            	Error: Error in function call
        	            	
        	            	  on ../../../modules/beta-public-cluster/cluster.tf line 938, in resource "google_container_node_pool" "pools":
        	            	 938:             hugepage_size_1g = try(coalesce(local.node_pools_hugepage_size_1g[each.value["name"]], local.node_pools_hugepage_size_1g["all"], null))
        	            	    ├────────────────
        	            	    │ each.value["name"] is "pool-03"
        	            	    │ local.node_pools_hugepage_size_1g is object with 8 attributes
        	            	    │ local.node_pools_hugepage_size_1g["all"] is ""
        	            	
        	            	Call to function "try" failed: no expression succeeded:
        	            	- Error in function call (at
        	            	../../../modules/beta-public-cluster/cluster.tf:938,36-45)
        	            	  Call to function "coalesce" failed: no non-null, non-empty-string arguments.
        	            	
        	            	At least one expression must produce a successful result
```

2025-04-25 23:29 UTC, DrFaust92 commented
local plans looks ok 🙏

2025-04-25 23:33 UTC, apeabody commented
/gcbrun

2025-04-25 23:34 UTC, DrFaust92 commented on autogen/main/cluster.tf.tmpl
> +            hugepage_size_2m = coalesce(local.node_pools_hugepage_size_2m[each.value["name"]], local.node_pools_hugepage_size_2m["all"], null)
done!

2025-04-26 00:08 UTC, DrFaust92 commented
This seemed to have failed fast /: . my ability to test this is limited as i can at most check this as a side branch on a running cluster

2025-04-26 00:11 UTC, apeabody commented
> This seemed to have failed fast /: . my ability to test this is limited as i can at most check this as a side branch on a running cluster

Flaky run, an API failed to active in time.  Re-running

2025-04-29 01:34 UTC, DrFaust92 commented
[apeabody](https://github.com/apeabody) any details?

2025-04-29 15:59 UTC, apeabody commented
> [apeabody](https://github.com/apeabody) any details?

Looks like need to adjust the test:
```
Step #54 - "apply node-pool-local":         	Error Trace:	/builder/home/go/pkg/mod/github.com/gruntwork-io/terratest@v0.48.2/modules/terraform/apply.go:34
Step #54 - "apply node-pool-local":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.17.6/pkg/tft/terraform.go:571
Step #54 - "apply node-pool-local":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.17.6/pkg/tft/terraform.go:630
Step #54 - "apply node-pool-local":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.17.6/pkg/tft/terraform.go:669
Step #54 - "apply node-pool-local":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.17.6/pkg/utils/stages.go:31
Step #54 - "apply node-pool-local":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.17.6/pkg/tft/terraform.go:669
Step #54 - "apply node-pool-local":         	Error:      	Received unexpected error:
Step #54 - "apply node-pool-local":         	            	FatalError{Underlying: error while running command: exit status 1; 
Step #54 - "apply node-pool-local":         	            	Error: error creating NodePool: googleapi: Error 400: 'pd-standard' with confidential storage mode: false is not compatible with the machine type c3-standard-4, please review the GCP online documentation for available persistent disk options.
Step #54 - "apply node-pool-local":         	            	Details:
Step #54 - "apply node-pool-local":         	            	[
Step #54 - "apply node-pool-local":         	            	  {
Step #54 - "apply node-pool-local":         	            	    "@type": "type.googleapis.com/google.rpc.RequestInfo",
Step #54 - "apply node-pool-local":         	            	    "requestId": "0x16c806feae5789fb"
Step #54 - "apply node-pool-local":         	            	  }
Step #54 - "apply node-pool-local":         	            	]
Step #54 - "apply node-pool-local":         	            	, badRequest
Step #54 - "apply node-pool-local":         	            	
Step #54 - "apply node-pool-local":         	            	  with module.example.module.gke.google_container_node_pool.pools["pool-05"],
Step #54 - "apply node-pool-local":         	            	  on ../../../modules/beta-public-cluster/cluster.tf line 644, in resource "google_container_node_pool" "pools":
Step #54 - "apply node-pool-local":         	            	 644: resource "google_container_node_pool" "pools" {
Step #54 - "apply node-pool-local":         	            	}
```

2025-05-05 23:34 UTC, DrFaust92 commented
[apeabody](https://github.com/apeabody) Ive attempted to make changes to accommodate this node type

2025-05-16 22:05 UTC, apeabody commented
/gcbrun

2025-05-16 23:58 UTC, apeabody commented
Thanks @DrFaust92 - Current INT test result:
```
Step #55 - "verify node-pool-local":         	Error:      	Not equal: 
Step #55 - "verify node-pool-local":         	            	expected: "1"
Step #55 - "verify node-pool-local":         	            	actual  : "2"
Step #55 - "verify node-pool-local":         	            	
Step #55 - "verify node-pool-local":         	            	Diff:
Step #55 - "verify node-pool-local":         	            	--- Expected
Step #55 - "verify node-pool-local":         	            	+++ Actual
Step #55 - "verify node-pool-local":         	            	@@ -1 +1 @@
Step #55 - "verify node-pool-local":         	            	-1
Step #55 - "verify node-pool-local":         	            	+2
Step #55 - "verify node-pool-local":         	Test:       	TestNodePool
Step #55 - "verify node-pool-local":         	Messages:   	For node "pool-05" path "config.linuxNodeConfig.hugepages.hugepageSize1g" expected "2" to match fixture "1"
```

2025-05-17 12:27 UTC, DrFaust92 commented
fail is correct, fixed test json. hopefully this is the last of it

2025-05-19 16:25 UTC, apeabody commented
/gcbrun

2025-05-29 18:08 UTC, apeabody commented
Hi @DrFaust92 - Can you please run `make docker_generate_docs` and update the PR. Thanks!

2025-05-30 03:00 UTC, DrFaust92 commented
[apeabody](https://github.com/apeabody) done

2025-05-30 16:24 UTC, apeabody commented
/gcbrun

2025-05-30 21:04 UTC, apeabody commented
/gcbrun

2025-05-30 23:20 UTC, apeabody approved these changes
Thanks for the contribution @DrFaust92!

2025-05-30 23:21 UTC, merged