feat: add confidential nodes example
terraform-google-modules/terraform-google-kubernetes-engine pull request #2227
Opened 2024-12-27 18:30 UTC by arthurlapertosa

2024-12-31 21:06 UTC, arthurlapertosa commented
cc @erlanderlo

2025-01-02 19:32 UTC, apeabody requested changes
Thanks for the contribution @arthurlapertosa!

A few initial notes to get the tests ready.

2025-01-02 19:32 UTC, apeabody commented on test/integration/confidential_safer_cluster/confidential_safer_cluster_test.go
> +func TestConfidentialSaferCluster(t *testing.T) {
Please add new `apply`, `validate`, `teardown` for `TestConfidentialSaferCluster` in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/build/int.cloudbuild.yaml#L37

You don't need to worry about `init` as that is automatically done for all examples.

2025-01-02 19:32 UTC, apeabody commented on test/integration/confidential_safer_cluster/confidential_safer_cluster_test.go
> +		for _, pth := range validateJSONPaths {
You could consider using the new `testutils.TGKEAssertGolden()`, example: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/test/integration/node_pool/node_pool_test.go#L63

Just include all the paths/values you want to test in [TestConfidentialSaferCluster.json](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2227/files#diff-1a9d26b22d2b881326a39f0bd31ae30fd9e9fe3c900d89cd372ee7d28e15000d)

2025-01-02 19:32 UTC, apeabody commented on test/integration/confidential_safer_cluster/confidential_safer_cluster_test.go
> +		// bpt.DefaultVerify(assert)
Please include `testutils.TGKEVerify(`) as it only verifies the resources, not the outputs

```suggestion
		// bpt.DefaultVerify(assert)
		testutils.TGKEVerify(t, bpt, assert) // Verify Resources
```

2025-01-02 19:32 UTC, apeabody commented on examples/confidential_safer_cluster/versions.tf
> +  required_version = ">= 0.13"
nit: we are moving to min TF v1.3

```suggestion
  required_version = ">= 1.3"
```

2025-02-03 17:10 UTC, apeabody commented
Hi @arthurlapertosa - Checking if you are still working on this PR.  Thanks!

2025-02-06 17:08 UTC, apeabody commented on build/int.cloudbuild.yaml
> +    - create-all
We finally deprecated the kitchen tests

```suggestion
    - init-all
```

2025-02-07 19:29 UTC, apeabody requested changes

2025-02-07 19:29 UTC, apeabody commented on test/fixtures/confidential_safer_cluster/example.tf
> +  project_id = var.project_ids[0]
```
Error: Error waiting to create Network: Error waiting for Creating Network: Quota 'NETWORKS' exceeded.  Limit: 15.0 globally.
	metric name = compute.googleapis.com/networks
	limit name = NETWORKS-per-project
	limit = 15
	dimensions = map[global:global]
```
Looks like we at at the network limit in this test project, let's try another:


```suggestion
  project_id = var.project_ids[1]
```

2025-02-10 21:34 UTC, apeabody commented
Hi @arthurlapertosa -  Looks like we are getting a perma-drift during the new test:

```
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185: Terraform used the selected providers to generate the following execution
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185: plan. Resource actions are indicated with the following symbols:
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:   ~ update in-place
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185: 
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185: Terraform will perform the following actions:
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185: 
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:   # module.example.module.gcp-network.module.subnets.google_compute_subnetwork.subnetwork["us-central1/confidential-safer-subnet"] will be updated in-place
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:   ~ resource "google_compute_subnetwork" "subnetwork" {
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:         id                         = "projects/ci-gke-3c5ba238-672b/regions/us-central1/subnetworks/confidential-safer-subnet"
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:         name                       = "confidential-safer-subnet"
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:       ~ private_ip_google_access   = true -> false
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:         # (18 unchanged attributes hidden)
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185: 
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:         # (2 unchanged blocks hidden)
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185:     }
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185: 
Step #88 - "verify test-confidential-safer-cluster": TestConfidentialSaferCluster 2025-02-10T19:23:45Z command.go:185: Plan: 0 to add, 1 to change, 0 to destroy.
```

Perhaps add `subnet_private_access = true` to your new test subnet.

2025-02-11 21:20 UTC, arthurlapertosa commented
@apeabody Thanks for the help!!
Looks like TestPrivateZonalWithNetworking is failing now? The output is too large, it's kinda difficult to know exactly what is going on...

2025-02-11 21:27 UTC, apeabody commented
Hmm - Looks like a new `resourceLabels` was automatically added to the cluster, once confirmed, we'll need to adjust the test:

```
Step #76 - "verify private-zonal-with-networking":         	            	Diff:
Step #76 - "verify private-zonal-with-networking":         	            	--- Expected
Step #76 - "verify private-zonal-with-networking":         	            	+++ Actual
Step #76 - "verify private-zonal-with-networking":         	            	@@ -1,2 +1,2 @@
Step #76 - "verify private-zonal-with-networking":         	            	-(map[string]interface {}) (len=15) {
Step #76 - "verify private-zonal-with-networking":         	            	+(map[string]interface {}) (len=16) {
Step #76 - "verify private-zonal-with-networking":         	            	  (string) (len=10) "diskSizeGb": (float64) 100,
Step #76 - "verify private-zonal-with-networking":         	            	@@ -26,2 +26,5 @@
Step #76 - "verify private-zonal-with-networking":         	            	  },
Step #76 - "verify private-zonal-with-networking":         	            	+ (string) (len=14) "resourceLabels": (map[string]interface {}) (len=1) {
Step #76 - "verify private-zonal-with-networking":         	            	+  (string) (len=37) "goog-gke-node-pool-provisioning-model": (string) (len=9) "on-demand"
Step #76 - "verify private-zonal-with-networking":         	            	+ },
Step #76 - "verify private-zonal-with-networking":         	            	  (string) (len=14) "serviceAccount": (string) (len=15) "SERVICE_ACCOUNT",
Step #76 - "verify private-zonal-with-networking":         	Test:       	TestPrivateZonalWithNetworking
```

2025-02-12 19:33 UTC, apeabody approved these changes
Thanks @arthurlapertosa!

2025-02-12 19:34 UTC, apeabody commented
Leave as `feat` as it makes minor changes to safer_cluster modules.

2025-02-12 19:34 UTC, merged