update shadow firewall support
terraform-google-modules/terraform-google-kubernetes-engine pull request #741
Opened 2020-11-11 04:28 UTC by ericyz

Add the shadow firewall rules to capture the package allowed by Google managed firewall rules. This can help users to add the visibility of the traffic between google-managed component and reduce security concerns

2020-11-11 04:36 UTC, morgante commented
@ericyz Please rebase on master.

2020-12-13 23:38 UTC, ericyz commented
Hey team, any feedback on this PR?

2020-12-15 23:07 UTC, morgante reviewed
@ericyz Can you explain more about the purpose of "shadow" firewall rules? Maybe we could have an explanation somewhere in the README or description?

2021-01-11 04:11 UTC, ericyz commented
Hi @morgante , I have added more descriptions to the TF variables. The purpose of shadow firewall is to gain more network insight of the packages flowing between GKE worker and master nodes.

2021-01-11 17:01 UTC, morgante requested changes

2021-01-11 17:01 UTC, morgante commented on firewall.tf
> +  description = "Managed by terraform gke module: A shadow firewall rule to match the fireall allow pod communication."
```suggestion
  description = "Managed by terraform gke module: A shadow firewall rule to match the default rule allowing pod communication."
```

2021-01-11 17:01 UTC, morgante commented on firewall.tf
> +  description = "Managed by terraform gke module: A shadow firewall rule to match the fireall allow master and woker nodes communication."
Typo:

```suggestion
  description = "Managed by terraform gke module: A shadow firewall rule to match the default rule allowing master and woker nodes communication."
```

2021-01-11 17:01 UTC, morgante commented on firewall.tf
> +  description = "Managed by terraform gke module: A shadow firewall rule to match the fireall allow woker nodes communication."
Typo:

```suggestion
  description = "Managed by terraform gke module: A shadow firewall rule to match the default rule allowing worker node communication."
```

2021-02-10 00:44 UTC, morgante requested changes

2021-02-10 00:44 UTC, morgante commented on autogen/main/firewall.tf.tmpl
> +  description = "Managed by terraform gke module: A shadow firewall rule to match the default rule allowing woker nodes communication."
```suggestion
  description = "Managed by terraform GKE module: A shadow firewall rule to match the default rule allowing worker nodes communication."
```

2021-02-10 00:44 UTC, morgante commented on autogen/main/firewall.tf.tmpl
> +  description = "Managed by terraform gke module: A shadow firewall rule to match the default rule allowing woker nodes communication."
```suggestion
  description = "Managed by Terraform GKE module: A shadow firewall rule to match the default rule allowing worker nodes communication."
```

2021-02-15 08:16 UTC, ericyz commented
Thanks @morgante for updating my type. Please review and let me know anything to update for the merge.

2021-02-16 17:02 UTC, morgante approved these changes

2021-02-16 17:03 UTC, merged