no beta usage in safer-cluster module
terraform-google-modules/terraform-google-kubernetes-engine pull request #766
Opened 2020-12-11 13:41 UTC by stubbi

As this is the `safer-cluster` module in contrast to the existing `beta-safer-cluster` module, I assume the `beta` is not needed or even not supposed to be here.

If the `beta` usage is intended here, feel free to close this PR without further comment.

2020-12-11 14:29 UTC, stubbi commented
Okay... considering these many errors.. I could try to address them. Is the change intended/of any help?

2020-12-11 18:34 UTC, morgante requested changes
This looks reasonable, but the change would need to be made in `autogen/safer-cluster/`. Please read the contributing guide: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CONTRIBUTING.md

2020-12-14 15:21 UTC, stubbi commented
@morgante thanks for the hint! Will have a look!

2020-12-17 15:37 UTC, stubbi commented
I'll close this PR for now. Won't have the time to work on this before Christmas. Might pick it up afterward.

2020-12-17 15:37 UTC, closed without merging