Add maintenance exclusions support
terraform-google-modules/terraform-google-kubernetes-engine pull request #781
Opened 2021-01-09 00:04 UTC by msgongora

fixes #780 
This feature has been [GA for about a year](https://groups.google.com/g/google-cloud-sdk-announce/c/CMmGr24zzP4/m/QaLEvGq_DAAJ) but looking at the [cluster template](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/81b0a9491d51546eedc6c1aabd368dc085c16b5e/autogen/main/cluster.tf.tmpl#L201) I realize most of the maintenance_policy features are still under beta, so I'm placing this PR under beta and probably I'm going to file another PR moving all those features, including this one, out of beta. Please let me know and I'll work on the 2nd PR as soon as I have time.

2021-01-09 00:20 UTC, msgongora commented
Also to mention that we could improve this implementation when support to 0.12 is dropped and we could fully use variable validation for instance. Maintenance exclusion has some [constraints or restrictions](https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions#configuring_a_maintenance_exclusion) that I think we could address better with a higher terraform version.

2021-01-09 03:26 UTC, bharathkkb requested changes
Thanks for the PR @msgongora 

You will need to bump the example provider versions as well. [Example](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/81b0a9491d51546eedc6c1aabd368dc085c16b5e/examples/simple_regional_beta/main.tf#L22)
We will also be [dropping support](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/779#issuecomment-756958504) for 0.12 in next release.

2021-01-09 23:47 UTC, msgongora commented
> You will need to bump the example provider versions as well. 
done, I see `docker_test_lint` clear of errors

2021-01-11 03:11 UTC, bharathkkb approved these changes

2021-01-11 03:11 UTC, merged