Add support for enable_l4_ilb_subsetting flag
terraform-google-modules/terraform-google-kubernetes-engine pull request #896
Opened 2021-05-16 03:42 UTC by Jberlinsky

Adds support for the `google_container_cluster` [enable_l4_ilb_subsetting](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enable_l4_ilb_subsetting) flag, which is particularly useful for [clusters that require more than 250 total Nodes and build ILBs](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#limits).

2021-05-16 06:03 UTC, Jberlinsky commented
A [cursory glance](https://github.com/hashicorp/terraform-provider-google/search?q=enable_l4_ilb_subsetting) of `terraform-google-provider` seems to indicate that, while documented, this property doesn't actually exist. Will investigate upstream.

2021-05-16 22:33 UTC, Jberlinsky commented
@bharathkkb @morgante @terraform-google-modules/cft-admins this is ready for review :)

2021-05-17 02:54 UTC, bharathkkb requested changes
Thanks for the PR @Jberlinsky 
Since we are bumping min provider versions this will be a breaking change.

2021-05-17 02:54 UTC, bharathkkb commented on autogen/main/variables.tf.tmpl
> +  description = "enabled - Enable L4 ILB Subsetting on the cluster"
Since we already have enabled in the description and variable name.
```suggestion
  description = "Enable L4 ILB Subsetting on the cluster"
```

2021-05-17 03:50 UTC, bharathkkb approved these changes

2021-05-17 03:50 UTC, merged

2021-05-17 16:07 UTC, gauravkr19 commented
Hi @Jberlinsky  @bharathkkb 

After this commit -  7531f90c943e01238180f0afdc3f0d43b0f04c59,
I am getting the following error:

> Error: Error waiting for creating GKE cluster: Failed to create cluster
> 
>   on .terraform/modules/jenkins-gke/modules/beta-public-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
>   22: resource "google_container_cluster" "primary" {

Is the issue because of this Change or global issue with GKE
https://status.cloud.google.com/incidents/sqeWSRmcrJZyE2zSrJ74

Appreciate any help on this.

2021-05-17 16:12 UTC, bharathkkb commented
Hi @gauravkr19 
Our integration tests which spins up the clusters passed and this flag is false by default. I am inclined to say it is not related to this change. If you are able to reproduce, please open an issue with that and we can debug further.

2021-05-17 16:50 UTC, gauravkr19 commented
Thanks @bharathkkb  for the quick response.

Can get the cluster up now, must be due to the outage at that point of time(tried 3 times).

By the way, I am implementing the jenkins-pipeline from below article and its working with terraform 0.12.24. 
Will have to update the terraform version soon.
https://cloud.google.com/architecture/managing-infrastructure-as-code-with-terraform-jenkins-and-gitops